import { CampusLocation, Product } from "./types";

export const PLATFORM_FEE_PERCENT = Number(process.env.PLATFORM_FEE_PERCENT || 2);
export const UNIVERSITY_DOMAIN = process.env.UNIVERSITY_DOMAIN || "vitap.ac.in";

export const CAMPUS_LOCATIONS: CampusLocation[] = [
  { id: "lib", name: "Central Library Ground Floor", type: "Academic", code: "LIB-GF", description: "Near the 24/7 self-study check-in desk" },
  { id: "food", name: "Food Street / Main Canteen", type: "Dining", code: "FOOD-STREET", description: "Central outdoor seating area" },
  { id: "sac", name: "Student Activity Center (SAC)", type: "Recreation", code: "SAC-FOYER", description: "Near indoor sports lobby" },
  { id: "ab1", name: "Academic Block 1 (AB-1)", type: "Academic", code: "AB1-PLAZA", description: "Main fountain entrance" },
  { id: "ab2", name: "Academic Block 2 (AB-2)", type: "Academic", code: "AB2-ATRIUM", description: "Ground floor atrium" },
  { id: "mh1", name: "Men's Hostel 1 (MH-1)", type: "Hostel", code: "MH-1", description: "MH-1 Guard desk & reception" },
  { id: "mh2", name: "Men's Hostel 2 (MH-2)", type: "Hostel", code: "MH-2", description: "MH-2 Common lounge" },
  { id: "mh3", name: "Men's Hostel 3 (MH-3)", type: "Hostel", code: "MH-3", description: "MH-3 Badminton court area" },
  { id: "lh1", name: "Ladies Hostel 1 (LH-1)", type: "Hostel", code: "LH-1", description: "LH-1 Main entry gate & visitor area" },
  { id: "lh2", name: "Ladies Hostel 2 (LH-2)", type: "Hostel", code: "LH-2", description: "LH-2 Gate check-in" },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Casio FX-991CW ClassWiz Scientific Calculator",
    description: "Mint condition scientific calculator. Used for 1 semester in Engineering Maths and Physics. Includes protective sliding cover and original manual. Allowed in all VIT-AP term exams.",
    category: "Calculators",
    price: 850,
    condition: "Like New",
    images: ["https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=600&auto=format&fit=crop&q=60"],
    location: "MH-2",
    status: "ACTIVE",
    sellerId: "user-rahul",
    sellerName: "Rahul Sharma",
    sellerEmail: "rahul.sharma2023@vitap.ac.in",
    sellerVerified: true,
    sellerRating: 4.9,
    sellerHostel: "MH-2",
    demandRating: "HIGH",
    views: 142,
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "prod-2",
    title: "Higher Engineering Mathematics by B.S. Grewal (44th Ed)",
    description: "Standard reference book for MAT1001 / MAT2001. Very clean pages with slight pencil annotations in chapter 3. Essential for 1st and 2nd year B.Tech students.",
    category: "Books",
    price: 380,
    condition: "Good",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=60"],
    location: "Library",
    status: "ACTIVE",
    sellerId: "user-priya",
    sellerName: "Priya V.",
    sellerEmail: "priya.v2022@vitap.ac.in",
    sellerVerified: true,
    sellerRating: 4.8,
    sellerHostel: "LH-1",
    demandRating: "HIGH",
    views: 98,
    createdAt: "2026-09-02T14:30:00Z"
  },
  {
    id: "prod-3",
    title: "Drafter + Engineering Drawing Kit (Omega)",
    description: "Complete mini drafter kit with sheet container, set squares, roller scale, and clips. Perfect for Mechanical/Civil/First-year engineering graphics course.",
    category: "Academic/Lab",
    price: 450,
    condition: "Good",
    images: ["https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600&auto=format&fit=crop&q=60"],
    location: "MH-1",
    status: "ACTIVE",
    sellerId: "user-karthik",
    sellerName: "Karthik Reddy",
    sellerEmail: "karthik.r2024@vitap.ac.in",
    sellerVerified: true,
    sellerRating: 5.0,
    sellerHostel: "MH-1",
    demandRating: "MEDIUM",
    views: 67,
    createdAt: "2026-09-03T09:15:00Z"
  },
  {
    id: "prod-4",
    title: "Logitech B100 USB Optical Mouse & Mousepad",
    description: "Plug-and-play wired mouse, highly responsive, tested in coding hackathons. Works with Windows/Mac/Linux.",
    category: "Electronics",
    price: 220,
    condition: "Like New",
    images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=60"],
    location: "Food Street",
    status: "ACTIVE",
    sellerId: "user-ananya",
    sellerName: "Ananya Patel",
    sellerEmail: "ananya.p2023@vitap.ac.in",
    sellerVerified: true,
    sellerRating: 4.7,
    sellerHostel: "LH-2",
    demandRating: "NORMAL",
    views: 45,
    createdAt: "2026-09-03T16:20:00Z"
  },
  {
    id: "prod-5",
    title: "Operating Systems Principles (Silberschatz Dinosaur Book)",
    description: "Willing to SWAP for 'Computer Networking: A Top-Down Approach' (Kurose/Ross) or sell for ₹400. In great condition.",
    category: "Swap",
    price: 400,
    condition: "Good",
    images: ["https://images.unsplash.com/photo-1532012164546-f432f2e37b73?w=600&auto=format&fit=crop&q=60"],
    location: "SAC",
    status: "ACTIVE",
    sellerId: "user-rohit",
    sellerName: "Rohit Verma",
    sellerEmail: "rohit.verma2022@vitap.ac.in",
    sellerVerified: true,
    sellerRating: 4.9,
    sellerHostel: "MH-3",
    isSwapAvailable: true,
    swapFor: "Computer Networking (Kurose/Ross)",
    demandRating: "HIGH",
    views: 112,
    createdAt: "2026-09-04T08:00:00Z"
  },
  {
    id: "prod-6",
    title: "DSA & Discrete Maths Handwritten Notes Bundle",
    description: "Complete semester handwritten notes, neatly bound. Covered all CAT-1, CAT-2, and FAT topics with solved previous year questions. Giving away for free to juniors!",
    category: "Free",
    price: 0,
    condition: "Good",
    images: ["https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&auto=format&fit=crop&q=60"],
    location: "Library",
    status: "ACTIVE",
    sellerId: "user-sneha",
    sellerName: "Sneha Roy",
    sellerEmail: "sneha.roy2021@vitap.ac.in",
    sellerVerified: true,
    sellerRating: 5.0,
    sellerHostel: "LH-1",
    isFree: true,
    demandRating: "HIGH",
    views: 210,
    createdAt: "2026-09-04T09:30:00Z"
  }
];
